export default {
    // SQL Lines for easy use

    // userFromId: `SELECT id, username, first_name AS 'firstName', last_name AS 'lastName', created_at AS 'createdAt'
    // from azdev.users
    // WHERE id = $1
    // `,

    // CREATE TABLES

    createUserTable: `CREATE TABLE IF NOT EXISTS Users (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      username varchar(50) NOT NULL,
      name varchar(50) NOT NULL
   );`,

    createResevationsTable: `CREATE TABLE IF NOT EXISTS Reservations (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      createdByUser integer REFERENCES Users NOT NULL,
      reservedRoom INTEGER REFERENCES Rooms NOT NULL,
      startDate VARCHAR(50) NOT NULL,
      endDate VARCHAR(50) NOT NULL
   );`,

    createRoomTable: `CREATE TABLE IF NOT EXISTS Rooms (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      number INTEGER NOT NULL,
      floor INTEGER NOT NULL DEFAULT 0,
      hasRoomService BOOLEAN NOT NULL, 
      hasView BOOLEAN NOT NULL,
      hasPool BOOLEAN NOT NULL
   );`,

   // ADD DUMMY DATA

    createDummyUsers: `
    INSERT INTO Users (username, name)
    VALUES 
      ('MollerSlayer69','Moller Mollersen'), 
      ('MyLittleBach', 'Bach Bachsen'), 
      ('GoesBrr','Gus Gustavson'), 
      ('DankBoi','Simon Simonsen')
    RETURNING id, username, name
    `,

    createDummyRooms: `
    INSERT INTO Rooms (number, floor, hasRoomService, hasView, hasPool)
    VALUES
        (0, 1, true, true, false),
        (1, 2, false, true, true),
        (2, 3, false, true, true),
        (4, 4, true, false, true),
        (69, 5, false, false, false),
        (420, 6, true, true, false)
    RETURNING 0, 0, false, false, false
    `,

    createDummyReservations:`
    INSERT INTO Reservations (createdByUser, reservedRoom, startdate, enddate)
    VALUES
        (1, 5, '20-04-1889 05:05:31', '20-04-1889 05:05:32'),
        (2, 1, '09-11-2008 06:09:35', '09-11-2008 06:09:36'),
        (3, 2, '21-03-1996 05:05:11', '21-03-1996 05:05:12'),
        (1, 6, '28-02-1999 00:01:01', '28-02-1999 00:01:02'),
        (3, 6, '04-05-2022 19:04:28', '04-05-2022 19:04:29')
    RETURNING 1, 1, '25-03-2022 19:04:28', '25-03-2022 19:04:29' 
    `,
    //-------------------------
    // QUERIES

    userFromId: `SELECT * from users WHERE id in ($1)`,
    
    getAllUsers: `SELECT * from users`,
    
    reservationInterval:`
    SELECT * from reservations WHERE 
    TO_TIMESTAMP(startdate, 'DD-MM-YYYY HH:MI:SS')  > TO_TIMESTAMP($1, 'DD-MM-YYYY HH:MI:SS') 
      AND TO_TIMESTAMP(startdate, 'DD-MM-YYYY HH:MI:SS') < TO_TIMESTAMP($2, 'DD-MM-YYYY HH:MI:SS')
    `, 
    
    getAllReservations: `SELECT * from Reservations`,

    getAllRooms: `SELECT * from Rooms`,
    
    // MUTATORS

    userInsert:`
    INSERT INTO users (username, name)
    VALUES ($1, $2)
    RETURNING id, username, name
    `,
    
    // Bachs afdeling start
    // ----- Bachs afdeling STOP----- BACH MÅ IKKE SKRIVE ANDRE STEDER -- IK' RØR MINE TING!!!

    reservationFromId:`
    SELECT * from Reservation WHERE id in ($1)
    `,

    roomFromId:`
    SELECT * from Rooms WHERE id in ($1)
    `,

    /* THIS WORKS ??!?!?! when hardcoded (which is bad but still)
        roomFromId:`
        SELECT * from Rooms WHERE id in (5, 1, 2, 6)
        `,
    */
}