export default {
    // SQL Lines for easy use

    // userFromId: `SELECT id, username, first_name AS "firstName", last_name AS "lastName", created_at AS "createdAt"
    // from azdev.users
    // WHERE id = $1
    // `,

    createUserTable: `CREATE TABLE IF NOT EXISTS Users (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      username VARCHAR(50) NOT NULL,
      name VARCHAR(50) NOT NULL,
      table_constraints
   );`,

    createResevationsTable: `CREATE TABLE IF NOT EXISTS Reservation (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      username VARCHAR(50) NOT NULL,
      name VARCHAR(50) NOT NULL,
      table_constraints
   );`,

    createRoomTable: `CREATE TABLE IF NOT EXISTS Room (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      username VARCHAR(50) NOT NULL,
      name VARCHAR(50) NOT NULL,
      table_constraints
   );`,

    userFromId: `SELECT * from azdev.users WHERE id = $1`,
    
    getAllUsers: `SELECT * from azdev.users`,
    
    createDummtyUsers:`
    INSERT INTO azdev.users (username, hashed_password, first_name, last_name, hashed_auth_token)
    VALUES ($1, 'password', $2, $3, 'authtoken')
    RETURNING id, username, first_name AS "firstName", last_name AS "lastName", created_at AS "createdAt"
    `

    userInsert: `
    INSERT INTO azdev.users (username, hashed_password, first_name, last_name, hashed_auth_token)
    VALUES ($1, 'password', $2, $3, 'authtoken')
    RETURNING id, username, first_name AS "firstName", last_name AS "lastName", created_at AS "createdAt"
  `
}