version: '3'
services:
  postgres:
    container_name: abe_pg
    image: postgres:latest
    expose:
      - 5433
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password