version: '3'
services:
  rabbitmq:
    container_name: abe_rabbit
    image: rabbitmq:3-management
    expose:
      - 15672
      - 5671
      - 5672
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password 
